name: Scheduled Crypto Analysis

on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run scheduled analysis
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        # Modify scheduled_analysis_task.py to read from environment variables
        # Import os module
        sed -i '1iimport os' scheduled_analysis_task.py
        # Change token and chat_id variables to read from environment
        sed -i 's/TELEGRAM_BOT_TOKEN = "YOUR_TELEGRAM_BOT_TOKEN"/TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN', TELEGRAM_BOT_TOKEN)/' scheduled_analysis_task.py
        sed -i 's/TELEGRAM_CHAT_ID = "YOUR_TELEGRAM_CHAT_ID"/TELEGRAM_CHAT_ID = os.getenv('TELEGRAM_CHAT_ID', TELEGRAM_CHAT_ID)/' scheduled_analysis_task.py

        python scheduled_analysis_task.py 
